language: python
python:
  - "3.6"
# command to install dependencies
before_install:  
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo apt-get install -y qtbase5-dev
  - pip install conan
  
# command to run tests
script:
  - conan create . david/testing   #or change test_generator/conanfile.txt accordingly
  - mkdir build && cd build
  - conan install ../test_generator -s compiler.libcxx=libstdc++11 --build=missing
  # qmake reference to qt4 qmake
  - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -makefile  ../test_generator/my_big_app.pro
  - make
  - ./tests/tests
